version: 2
project_name: MacOSVK
gitlab_urls:
  api: "{{ .Env.CI_API_V4_URL }}"
  download: "{{ .Env.CI_SERVER_URL }}"
  skip_tls_verify: true
  use_package_registry: true
  use_job_token: true
dist: ./build
builds:
- main: ./cmd/virtual-kubelet
  binary: ./MacOSVK.app
  flags:
  - -trimpath
  goos:
  - darwin
  goarch:
  - arm64
  ldflags:
  # one-line ldflags to bypass the goreleaser bugs
  # the git tree state is guaranteed to be clean by goreleaser
  - -w -s -buildid= -X main.buildVersion={{ .ShortCommit }}
  mod_timestamp: "{{ .CommitTimestamp }}"
  hooks:
    post:
      - codesign --deep -s "{{ .Env.RELEASE_CERTIFICATE_NAME }}" --entitlements "{{ .Env.ROOT_DIR }}/resources/release.entitlements" "{{ .Path }}"
      - mv {{ .Path }} "{{ dir .Path }}/MacOSVK"
      - mkdir -p "{{ .Path }}/Contents/MacOS"
      - cp "{{ .Env.RELEASE_PROVISION_PROFILE_PATH }}" "{{ .Path }}/Contents/embedded.provisionprofile"
      - mv "{{ dir .Path }}/MacOSVK" "{{ .Path }}/Contents/MacOS/"

archives:
  - formats: zip
    files:
    - LICENSE
    - src: build/MacOSVK_darwin_arm64_v8.0/MacOSVK.app
      dst: MacOSVK.app
